# Pre-commit hooks configuration for Bitfinex Maker-Kit
# Runs the same code quality checks as CI pipeline to prevent failing commits
# Install: pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # Ruff - Fast Python linter and formatter (matches CI configuration)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.5
    hooks:
      # Linting check with auto-fix
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^(bitfinex_maker_kit|tests)/.*\.py$
      
      # Code formatting check  
      - id: ruff-format
        files: ^(bitfinex_maker_kit|tests)/.*\.py$

  # MyPy - Static type checking (matches CI configuration)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.0
    hooks:
      - id: mypy
        files: ^bitfinex_maker_kit/.*\.py$
        additional_dependencies: [types-psutil]
        args: [--config-file=pyproject.toml, --ignore-missing-imports]

  # Security scanning with Bandit (simplified for pre-commit)
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: [--skip, B101]
        files: ^bitfinex_maker_kit/.*\.py$

  # Built-in hooks for basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        files: ^(bitfinex_maker_kit|tests)/.*\.(py|yaml|yml|md|toml)$
      - id: end-of-file-fixer
        files: ^(bitfinex_maker_kit|tests)/.*\.(py|yaml|yml|md|toml)$
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-merge-conflict
      - id: debug-statements
        files: ^(bitfinex_maker_kit|tests)/.*\.py$
      - id: detect-private-key

# Configuration
default_install_hook_types: [pre-commit]
default_stages: [pre-commit]
fail_fast: false  # Run all hooks even if one fails
minimum_pre_commit_version: "3.0.0"

# CI configuration for pre-commit.ci
ci:
    autofix_commit_msg: '[pre-commit.ci] auto fixes'
    autofix_prs: true
    autoupdate_schedule: monthly