name: Enforce Branch Flow

on:
  pull_request:
    branches:
      - main

jobs:
  check-source-branch:
    name: Validate PR Source
    runs-on: ubuntu-latest
    
    steps:
    - name: Check PR is from develop or release branch
      env:
        SOURCE_BRANCH: ${{ github.head_ref }}
        BASE_BRANCH: ${{ github.base_ref }}
      run: |
        echo "PR from: $SOURCE_BRANCH to: $BASE_BRANCH"
        
        # Validate base branch is main
        if [[ "$BASE_BRANCH" != "main" ]]; then
          echo "⚠️ Warning: Unexpected base branch: $BASE_BRANCH"
          echo "This workflow only validates PRs to main branch"
          exit 0
        fi
        
        # Allow PRs from develop, release/*, or hotfix/* branches
        # Hotfixes can go directly to main for critical production fixes
        if [[ "$SOURCE_BRANCH" == "develop" ]] || \
           [[ "$SOURCE_BRANCH" =~ ^release/.* ]] || \
           [[ "$SOURCE_BRANCH" =~ ^hotfix/.* ]]; then
          echo "✅ Valid PR: $SOURCE_BRANCH → main"
          exit 0
        else
          echo "❌ Invalid PR: Only 'develop', 'release/*', or 'hotfix/*' branches can merge to main"
          echo "Current branch: $SOURCE_BRANCH"
          echo ""
          echo "Please follow the Git Flow:"
          echo "For normal features/fixes:"
          echo "1. Create feature/*, fix/*, chore/*, refactor/*, etc. branch"
          echo "2. Merge to develop first"
          echo "3. Create a release from develop"
          echo "4. Merge the release to main"
          echo ""
          echo "For critical production fixes:"
          echo "1. Create hotfix/* branch from main"
          echo "2. Merge directly to main"
          echo "3. Back-merge to develop"
          exit 1
        fi